spring:
  application:
    name: demo2
  datasource:
    url: jdbc:mysql://118.31.221.252:3306/test?serverTimezone=GMT%2B8
    username: root
    password: Gl880329!
    driver-class-name: com.mysql.cj.jdbc.Driver
